[package]
name = "voulr"
version = "2.0.5"

edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.30", features = ["derive"] }
crossterm = "0.28.1"
inquire = "0.7.5"
