name: publish cli
on:
    push:
        tags:
            - "v*"

jobs:
    build:
        name: build ${{ matrix.target }}
        runs-on: ${{ matrix.name }}
        strategy:
            matrix:
                include:
                    - name: macos apple silicon
                      target: aarch64-apple-darwin
                      os: macos-latest

                    - name: macos intel
                      target: x86_64-apple-darwin
                      os: macos-latest

                    - name: linux
                      target: x86_64-unknown-linux-gnu
                      os: ubuntu-latest

                    - name: windows
                      target: x86_64-pc-windows-msvc
                      os: windows-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: install rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: build (native)
              if: matrix.name != 'linux'
              run: cargo build --release --target ${{ matrix.target }}

            - name: build (cross)
              if: matrix.name == 'linux'
              run: |
                  cargo install cross
                  cross build --release --target ${{ matrix.target }}

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/

    publish:
        needs: build
        name: publish to npm
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: download artifacts
              uses: actions/download-artifact@v4

            - name: compress
              run: |
                  mkdir compressed
                  tar -czvf compressed/voulr-macos-silicon.tar.gz aarch64-apple-darwin/voulr
                  tar -czvf compressed/voulr-macos-intel.tar.gz x86_64-apple-darwin/voulr
                  tar -czvf compressed/voulr-linux.tar.gz x86_64-unknown-linux-gnu/voulr
                  tar -czvf compressed/voulr-windows.tar.gz x86_64-pc-windows-msvc/voulr.exe

            - name: release
              uses: softprops/action-gh-release@v2
              with:
                  files: compressed/*

            - name: install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"
                  provenance: true

            - name: publish npm package
              run: |
                  cd ./apps/cli/npm
                  cp ../../../README.md .
                  npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
